steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.listener', '-t', 'gcr.io/$PROJECT_ID/plannery-slack-listener', '.']
images:
  - 'gcr.io/$PROJECT_ID/plannery-slack-listener'
